// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: machines.sql

package db

import (
	"context"
	"database/sql"
)

const createMachine = `-- name: CreateMachine :one
INSERT INTO machines (machine_name, quantity, estimate_time, type_id) 
VALUES ($1, $2, $3, $4) 
RETURNING id, machine_name, quantity, estimate_time, type_id, created_at, updated_at
`

type CreateMachineParams struct {
	MachineName  string
	Quantity     int32
	EstimateTime int32
	TypeID       sql.NullInt32
}

func (q *Queries) CreateMachine(ctx context.Context, arg CreateMachineParams) (Machine, error) {
	row := q.db.QueryRowContext(ctx, createMachine,
		arg.MachineName,
		arg.Quantity,
		arg.EstimateTime,
		arg.TypeID,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.MachineName,
		&i.Quantity,
		&i.EstimateTime,
		&i.TypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMachine = `-- name: DeleteMachine :exec
DELETE FROM machines 
WHERE id = $1
`

func (q *Queries) DeleteMachine(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteMachine, id)
	return err
}

const getMachine = `-- name: GetMachine :one
SELECT id, machine_name, quantity, estimate_time, type_id, created_at, updated_at 
FROM machines 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMachine(ctx context.Context, id int32) (Machine, error) {
	row := q.db.QueryRowContext(ctx, getMachine, id)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.MachineName,
		&i.Quantity,
		&i.EstimateTime,
		&i.TypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMachines = `-- name: ListMachines :many
SELECT id, machine_name, quantity, estimate_time, type_id, created_at, updated_at 
FROM machines 
ORDER BY machine_name
`

func (q *Queries) ListMachines(ctx context.Context) ([]Machine, error) {
	rows, err := q.db.QueryContext(ctx, listMachines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.MachineName,
			&i.Quantity,
			&i.EstimateTime,
			&i.TypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMachine = `-- name: UpdateMachine :one
UPDATE machines 
SET machine_name = $2, quantity = $3, estimate_time = $4, updated_at = NOW() 
WHERE id = $1 
RETURNING id, machine_name, quantity, estimate_time, type_id, created_at, updated_at
`

type UpdateMachineParams struct {
	ID           int32
	MachineName  string
	Quantity     int32
	EstimateTime int32
}

func (q *Queries) UpdateMachine(ctx context.Context, arg UpdateMachineParams) (Machine, error) {
	row := q.db.QueryRowContext(ctx, updateMachine,
		arg.ID,
		arg.MachineName,
		arg.Quantity,
		arg.EstimateTime,
	)
	var i Machine
	err := row.Scan(
		&i.ID,
		&i.MachineName,
		&i.Quantity,
		&i.EstimateTime,
		&i.TypeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
