// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type AssignmentStatus string

const (
	AssignmentStatusPending AssignmentStatus = "pending"
	AssignmentStatusProcess AssignmentStatus = "process"
	AssignmentStatusFinish  AssignmentStatus = "finish"
)

func (e *AssignmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssignmentStatus(s)
	case string:
		*e = AssignmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssignmentStatus: %T", src)
	}
	return nil
}

type NullAssignmentStatus struct {
	AssignmentStatus AssignmentStatus
	Valid            bool // Valid is true if AssignmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssignmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssignmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssignmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssignmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssignmentStatus), nil
}

type TaskStatus string

const (
	TaskStatusDraft      TaskStatus = "draft"
	TaskStatusPending    TaskStatus = "pending"
	TaskStatusProcessing TaskStatus = "processing"
	TaskStatusFinish     TaskStatus = "finish"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus
	Valid      bool // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type Machine struct {
	ID           int32
	MachineName  string
	Quantity     int32
	EstimateTime int32
	TypeID       sql.NullInt32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Role struct {
	ID        int32
	RoleName  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type SubTask struct {
	ID             int32
	TaskID         int32
	TypeID         int32
	SubTaskName    sql.NullString
	Description    sql.NullString
	EstimateEffort sql.NullInt32
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type Task struct {
	ID        int32
	TaskName  string
	Status    TaskStatus
	Priority  int32
	StartTime sql.NullTime
	EndTime   sql.NullTime
	Note      sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TaskType struct {
	ID          int32
	TypeName    string
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type User struct {
	ID        int32
	Name      string
	Email     string
	RoleID    int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserToSubTask struct {
	ID         int32
	UserID     int32
	SubTaskID  int32
	Report     sql.NullString
	Status     NullAssignmentStatus
	AssignedAt sql.NullTime
	UpdatedAt  sql.NullTime
}

type UserToType struct {
	UserID    int32
	TypeID    int32
	CreatedAt sql.NullTime
}
