// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sub_tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createSubTask = `-- name: CreateSubTask :one
INSERT INTO sub_tasks (task_id, type_id, sub_task_name, description, estimate_effort)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, task_id, type_id, sub_task_name, description, estimate_effort, created_at, updated_at
`

type CreateSubTaskParams struct {
	TaskID         int32
	TypeID         int32
	SubTaskName    sql.NullString
	Description    sql.NullString
	EstimateEffort sql.NullInt32
}

func (q *Queries) CreateSubTask(ctx context.Context, arg CreateSubTaskParams) (SubTask, error) {
	row := q.db.QueryRowContext(ctx, createSubTask,
		arg.TaskID,
		arg.TypeID,
		arg.SubTaskName,
		arg.Description,
		arg.EstimateEffort,
	)
	var i SubTask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TypeID,
		&i.SubTaskName,
		&i.Description,
		&i.EstimateEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubTask = `-- name: DeleteSubTask :exec
DELETE FROM sub_tasks
WHERE id = $1
`

func (q *Queries) DeleteSubTask(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSubTask, id)
	return err
}

const getSubTask = `-- name: GetSubTask :one
SELECT id, task_id, type_id, sub_task_name, description, estimate_effort, created_at, updated_at FROM sub_tasks
WHERE id = $1
`

func (q *Queries) GetSubTask(ctx context.Context, id int32) (SubTask, error) {
	row := q.db.QueryRowContext(ctx, getSubTask, id)
	var i SubTask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TypeID,
		&i.SubTaskName,
		&i.Description,
		&i.EstimateEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubTasksByTaskID = `-- name: GetSubTasksByTaskID :many
SELECT id, task_id, type_id, sub_task_name, description, estimate_effort, created_at, updated_at FROM sub_tasks
WHERE task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetSubTasksByTaskID(ctx context.Context, taskID int32) ([]SubTask, error) {
	rows, err := q.db.QueryContext(ctx, getSubTasksByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubTask
	for rows.Next() {
		var i SubTask
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TypeID,
			&i.SubTaskName,
			&i.Description,
			&i.EstimateEffort,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubTask = `-- name: UpdateSubTask :one
UPDATE sub_tasks
SET sub_task_name = $2, description = $3, estimate_effort = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, task_id, type_id, sub_task_name, description, estimate_effort, created_at, updated_at
`

type UpdateSubTaskParams struct {
	ID             int32
	SubTaskName    sql.NullString
	Description    sql.NullString
	EstimateEffort sql.NullInt32
}

func (q *Queries) UpdateSubTask(ctx context.Context, arg UpdateSubTaskParams) (SubTask, error) {
	row := q.db.QueryRowContext(ctx, updateSubTask,
		arg.ID,
		arg.SubTaskName,
		arg.Description,
		arg.EstimateEffort,
	)
	var i SubTask
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TypeID,
		&i.SubTaskName,
		&i.Description,
		&i.EstimateEffort,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
