// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task_types.sql

package db

import (
	"context"
	"database/sql"
)

const createTaskType = `-- name: CreateTaskType :one
INSERT INTO task_types (type_name, description) 
VALUES ($1, $2) 
RETURNING id, type_name, description, created_at, updated_at
`

type CreateTaskTypeParams struct {
	TypeName    string
	Description sql.NullString
}

func (q *Queries) CreateTaskType(ctx context.Context, arg CreateTaskTypeParams) (TaskType, error) {
	row := q.db.QueryRowContext(ctx, createTaskType, arg.TypeName, arg.Description)
	var i TaskType
	err := row.Scan(
		&i.ID,
		&i.TypeName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskType = `-- name: DeleteTaskType :exec
DELETE FROM task_types 
WHERE id = $1
`

func (q *Queries) DeleteTaskType(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTaskType, id)
	return err
}

const getMachineUsageByTaskType = `-- name: GetMachineUsageByTaskType :many
SELECT 
    st.type_id,
    COUNT(uts.id) as usage_count
FROM sub_tasks st
JOIN user_to_sub_task uts ON st.id = uts.sub_task_id
JOIN tasks t ON st.task_id = t.id
WHERE t.status IN ('pending', 'processing')
GROUP BY st.type_id
`

type GetMachineUsageByTaskTypeRow struct {
	TypeID     int32
	UsageCount int64
}

func (q *Queries) GetMachineUsageByTaskType(ctx context.Context) ([]GetMachineUsageByTaskTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getMachineUsageByTaskType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMachineUsageByTaskTypeRow
	for rows.Next() {
		var i GetMachineUsageByTaskTypeRow
		if err := rows.Scan(&i.TypeID, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMachinesByTaskType = `-- name: GetMachinesByTaskType :many
SELECT m.id, m.machine_name, m.quantity, m.estimate_time, m.type_id, m.created_at, m.updated_at 
FROM machines m 
WHERE m.type_id = $1 
ORDER BY m.id
`

func (q *Queries) GetMachinesByTaskType(ctx context.Context, typeID sql.NullInt32) ([]Machine, error) {
	rows, err := q.db.QueryContext(ctx, getMachinesByTaskType, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Machine
	for rows.Next() {
		var i Machine
		if err := rows.Scan(
			&i.ID,
			&i.MachineName,
			&i.Quantity,
			&i.EstimateTime,
			&i.TypeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskType = `-- name: GetTaskType :one
SELECT id, type_name, description, created_at, updated_at 
FROM task_types 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaskType(ctx context.Context, id int32) (TaskType, error) {
	row := q.db.QueryRowContext(ctx, getTaskType, id)
	var i TaskType
	err := row.Scan(
		&i.ID,
		&i.TypeName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskTypeWithMachines = `-- name: GetTaskTypeWithMachines :one
SELECT t.id, t.type_name, t.description, t.created_at, t.updated_at 
FROM task_types t 
WHERE t.id = $1 LIMIT 1
`

func (q *Queries) GetTaskTypeWithMachines(ctx context.Context, id int32) (TaskType, error) {
	row := q.db.QueryRowContext(ctx, getTaskTypeWithMachines, id)
	var i TaskType
	err := row.Scan(
		&i.ID,
		&i.TypeName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTaskTypes = `-- name: ListTaskTypes :many
SELECT id, type_name, description, created_at, updated_at 
FROM task_types 
ORDER BY id
`

func (q *Queries) ListTaskTypes(ctx context.Context) ([]TaskType, error) {
	rows, err := q.db.QueryContext(ctx, listTaskTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskType
	for rows.Next() {
		var i TaskType
		if err := rows.Scan(
			&i.ID,
			&i.TypeName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskType = `-- name: UpdateTaskType :one
UPDATE task_types 
SET type_name = $2, description = $3, updated_at = NOW() 
WHERE id = $1 
RETURNING id, type_name, description, created_at, updated_at
`

type UpdateTaskTypeParams struct {
	ID          int32
	TypeName    string
	Description sql.NullString
}

func (q *Queries) UpdateTaskType(ctx context.Context, arg UpdateTaskTypeParams) (TaskType, error) {
	row := q.db.QueryRowContext(ctx, updateTaskType, arg.ID, arg.TypeName, arg.Description)
	var i TaskType
	err := row.Scan(
		&i.ID,
		&i.TypeName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
