// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (task_name, status, priority, start_time, end_time, note, report)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at
`

type CreateTaskParams struct {
	TaskName  string
	Status    TaskStatus
	Priority  int32
	StartTime sql.NullTime
	EndTime   sql.NullTime
	Note      sql.NullString
	Report    sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TaskName,
		arg.Status,
		arg.Priority,
		arg.StartTime,
		arg.EndTime,
		arg.Note,
		arg.Report,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.Status,
		&i.Priority,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getDraftTasksSortedByPriority = `-- name: GetDraftTasksSortedByPriority :many
SELECT id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at FROM tasks
WHERE status = 'draft'
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) GetDraftTasksSortedByPriority(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getDraftTasksSortedByPriority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskName,
			&i.Status,
			&i.Priority,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Report,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTasksSortedByPriority = `-- name: GetPendingTasksSortedByPriority :many
SELECT id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at FROM tasks
WHERE status = 'pending'
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) GetPendingTasksSortedByPriority(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getPendingTasksSortedByPriority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskName,
			&i.Status,
			&i.Priority,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Report,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessingTasksSortedByPriority = `-- name: GetProcessingTasksSortedByPriority :many
SELECT id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at FROM tasks
WHERE status = 'processing'
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) GetProcessingTasksSortedByPriority(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getProcessingTasksSortedByPriority)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskName,
			&i.Status,
			&i.Priority,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Report,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int32) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.Status,
		&i.Priority,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksByStatus = `-- name: GetTasksByStatus :many
SELECT id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at FROM tasks
WHERE status = $1
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) GetTasksByStatus(ctx context.Context, status TaskStatus) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskName,
			&i.Status,
			&i.Priority,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Report,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TaskName,
			&i.Status,
			&i.Priority,
			&i.StartTime,
			&i.EndTime,
			&i.Note,
			&i.Report,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET task_name = $2, status = $3, priority = $4, start_time = $5, end_time = $6, note = $7, report = $8, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at
`

type UpdateTaskParams struct {
	ID        int32
	TaskName  string
	Status    TaskStatus
	Priority  int32
	StartTime sql.NullTime
	EndTime   sql.NullTime
	Note      sql.NullString
	Report    sql.NullString
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.TaskName,
		arg.Status,
		arg.Priority,
		arg.StartTime,
		arg.EndTime,
		arg.Note,
		arg.Report,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.Status,
		&i.Priority,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     int32
	Status TaskStatus
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.Status,
		&i.Priority,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatusWithReport = `-- name: UpdateTaskStatusWithReport :one
UPDATE tasks
SET status = $2, report = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, task_name, status, priority, start_time, end_time, note, report, created_at, updated_at
`

type UpdateTaskStatusWithReportParams struct {
	ID     int32
	Status TaskStatus
	Report sql.NullString
}

func (q *Queries) UpdateTaskStatusWithReport(ctx context.Context, arg UpdateTaskStatusWithReportParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatusWithReport, arg.ID, arg.Status, arg.Report)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TaskName,
		&i.Status,
		&i.Priority,
		&i.StartTime,
		&i.EndTime,
		&i.Note,
		&i.Report,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
