// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_to_sub_task.sql

package db

import (
	"context"
	"database/sql"
)

const createUserSubTaskAssignment = `-- name: CreateUserSubTaskAssignment :one
INSERT INTO user_to_sub_task (user_id, sub_task_id, report, status)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, sub_task_id, report, status, assigned_at, updated_at
`

type CreateUserSubTaskAssignmentParams struct {
	UserID    int32
	SubTaskID int32
	Report    sql.NullString
	Status    NullAssignmentStatus
}

func (q *Queries) CreateUserSubTaskAssignment(ctx context.Context, arg CreateUserSubTaskAssignmentParams) (UserToSubTask, error) {
	row := q.db.QueryRowContext(ctx, createUserSubTaskAssignment,
		arg.UserID,
		arg.SubTaskID,
		arg.Report,
		arg.Status,
	)
	var i UserToSubTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubTaskID,
		&i.Report,
		&i.Status,
		&i.AssignedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserSubTaskAssignment = `-- name: DeleteUserSubTaskAssignment :exec
DELETE FROM user_to_sub_task
WHERE id = $1
`

func (q *Queries) DeleteUserSubTaskAssignment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubTaskAssignment, id)
	return err
}

const deleteUserSubTaskAssignmentByUserAndSubTask = `-- name: DeleteUserSubTaskAssignmentByUserAndSubTask :exec
DELETE FROM user_to_sub_task
WHERE user_id = $1 AND sub_task_id = $2
`

type DeleteUserSubTaskAssignmentByUserAndSubTaskParams struct {
	UserID    int32
	SubTaskID int32
}

func (q *Queries) DeleteUserSubTaskAssignmentByUserAndSubTask(ctx context.Context, arg DeleteUserSubTaskAssignmentByUserAndSubTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubTaskAssignmentByUserAndSubTask, arg.UserID, arg.SubTaskID)
	return err
}

const getAssignmentsBySubTaskID = `-- name: GetAssignmentsBySubTaskID :many
SELECT id, user_id, sub_task_id, report, status, assigned_at, updated_at FROM user_to_sub_task
WHERE sub_task_id = $1
ORDER BY assigned_at ASC
`

func (q *Queries) GetAssignmentsBySubTaskID(ctx context.Context, subTaskID int32) ([]UserToSubTask, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsBySubTaskID, subTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserToSubTask
	for rows.Next() {
		var i UserToSubTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubTaskID,
			&i.Report,
			&i.Status,
			&i.AssignedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsByTaskID = `-- name: GetAssignmentsByTaskID :many
SELECT uts.id, uts.user_id, uts.sub_task_id, uts.report, uts.status, uts.assigned_at, uts.updated_at FROM user_to_sub_task uts
JOIN sub_tasks st ON uts.sub_task_id = st.id
WHERE st.task_id = $1
ORDER BY uts.assigned_at ASC
`

func (q *Queries) GetAssignmentsByTaskID(ctx context.Context, taskID int32) ([]UserToSubTask, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserToSubTask
	for rows.Next() {
		var i UserToSubTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubTaskID,
			&i.Report,
			&i.Status,
			&i.AssignedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsByUserID = `-- name: GetAssignmentsByUserID :many
SELECT id, user_id, sub_task_id, report, status, assigned_at, updated_at FROM user_to_sub_task
WHERE user_id = $1
ORDER BY assigned_at DESC
`

func (q *Queries) GetAssignmentsByUserID(ctx context.Context, userID int32) ([]UserToSubTask, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserToSubTask
	for rows.Next() {
		var i UserToSubTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubTaskID,
			&i.Report,
			&i.Status,
			&i.AssignedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubTaskAssignment = `-- name: GetUserSubTaskAssignment :one
SELECT id, user_id, sub_task_id, report, status, assigned_at, updated_at FROM user_to_sub_task
WHERE id = $1
`

func (q *Queries) GetUserSubTaskAssignment(ctx context.Context, id int32) (UserToSubTask, error) {
	row := q.db.QueryRowContext(ctx, getUserSubTaskAssignment, id)
	var i UserToSubTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubTaskID,
		&i.Report,
		&i.Status,
		&i.AssignedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignmentStatus = `-- name: UpdateAssignmentStatus :one
UPDATE user_to_sub_task
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, sub_task_id, report, status, assigned_at, updated_at
`

type UpdateAssignmentStatusParams struct {
	ID     int32
	Status NullAssignmentStatus
}

func (q *Queries) UpdateAssignmentStatus(ctx context.Context, arg UpdateAssignmentStatusParams) (UserToSubTask, error) {
	row := q.db.QueryRowContext(ctx, updateAssignmentStatus, arg.ID, arg.Status)
	var i UserToSubTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubTaskID,
		&i.Report,
		&i.Status,
		&i.AssignedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssignmentStatusAndReport = `-- name: UpdateAssignmentStatusAndReport :one
UPDATE user_to_sub_task
SET status = $2, report = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, sub_task_id, report, status, assigned_at, updated_at
`

type UpdateAssignmentStatusAndReportParams struct {
	ID     int32
	Status NullAssignmentStatus
	Report sql.NullString
}

func (q *Queries) UpdateAssignmentStatusAndReport(ctx context.Context, arg UpdateAssignmentStatusAndReportParams) (UserToSubTask, error) {
	row := q.db.QueryRowContext(ctx, updateAssignmentStatusAndReport, arg.ID, arg.Status, arg.Report)
	var i UserToSubTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubTaskID,
		&i.Report,
		&i.Status,
		&i.AssignedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSubTaskAssignment = `-- name: UpdateUserSubTaskAssignment :one
UPDATE user_to_sub_task
SET report = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, sub_task_id, report, status, assigned_at, updated_at
`

type UpdateUserSubTaskAssignmentParams struct {
	ID     int32
	Report sql.NullString
}

func (q *Queries) UpdateUserSubTaskAssignment(ctx context.Context, arg UpdateUserSubTaskAssignmentParams) (UserToSubTask, error) {
	row := q.db.QueryRowContext(ctx, updateUserSubTaskAssignment, arg.ID, arg.Report)
	var i UserToSubTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubTaskID,
		&i.Report,
		&i.Status,
		&i.AssignedAt,
		&i.UpdatedAt,
	)
	return i, err
}
