// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_to_sub_task.sql

package db

import (
	"context"
	"database/sql"
)

const checkUserHasActiveTasks = `-- name: CheckUserHasActiveTasks :one
SELECT EXISTS(
    SELECT 1 FROM user_to_sub_task uts
    JOIN sub_tasks st ON uts.sub_task_id = st.id  
    JOIN tasks t ON st.task_id = t.id
    WHERE uts.user_id = $1 AND t.status IN ('draft', 'pending', 'processing')
) AS has_active_tasks
`

func (q *Queries) CheckUserHasActiveTasks(ctx context.Context, userID int32) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserHasActiveTasks, userID)
	var has_active_tasks bool
	err := row.Scan(&has_active_tasks)
	return has_active_tasks, err
}

const createUserSubTaskAssignment = `-- name: CreateUserSubTaskAssignment :one
INSERT INTO user_to_sub_task (user_id, sub_task_id)
VALUES ($1, $2)
RETURNING id, user_id, sub_task_id, assigned_at, updated_at
`

type CreateUserSubTaskAssignmentParams struct {
	UserID    int32
	SubTaskID int32
}

func (q *Queries) CreateUserSubTaskAssignment(ctx context.Context, arg CreateUserSubTaskAssignmentParams) (UserToSubTask, error) {
	row := q.db.QueryRowContext(ctx, createUserSubTaskAssignment, arg.UserID, arg.SubTaskID)
	var i UserToSubTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubTaskID,
		&i.AssignedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignmentsForDraftTasks = `-- name: DeleteAssignmentsForDraftTasks :exec
DELETE FROM user_to_sub_task
USING sub_tasks, tasks
WHERE user_to_sub_task.sub_task_id = sub_tasks.id 
  AND sub_tasks.task_id = tasks.id 
  AND tasks.status = 'draft'
`

func (q *Queries) DeleteAssignmentsForDraftTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAssignmentsForDraftTasks)
	return err
}

const deleteUserSubTaskAssignment = `-- name: DeleteUserSubTaskAssignment :exec
DELETE FROM user_to_sub_task
WHERE id = $1
`

func (q *Queries) DeleteUserSubTaskAssignment(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubTaskAssignment, id)
	return err
}

const deleteUserSubTaskAssignmentByUserAndSubTask = `-- name: DeleteUserSubTaskAssignmentByUserAndSubTask :exec
DELETE FROM user_to_sub_task
WHERE user_id = $1 AND sub_task_id = $2
`

type DeleteUserSubTaskAssignmentByUserAndSubTaskParams struct {
	UserID    int32
	SubTaskID int32
}

func (q *Queries) DeleteUserSubTaskAssignmentByUserAndSubTask(ctx context.Context, arg DeleteUserSubTaskAssignmentByUserAndSubTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubTaskAssignmentByUserAndSubTask, arg.UserID, arg.SubTaskID)
	return err
}

const getActiveAssignmentsByUserID = `-- name: GetActiveAssignmentsByUserID :many
SELECT uts.id, uts.user_id, uts.sub_task_id, uts.assigned_at, uts.updated_at, st.type_id FROM user_to_sub_task uts
JOIN sub_tasks st ON uts.sub_task_id = st.id
WHERE uts.user_id = $1
ORDER BY uts.assigned_at DESC
`

type GetActiveAssignmentsByUserIDRow struct {
	ID         int32
	UserID     int32
	SubTaskID  int32
	AssignedAt sql.NullTime
	UpdatedAt  sql.NullTime
	TypeID     int32
}

func (q *Queries) GetActiveAssignmentsByUserID(ctx context.Context, userID int32) ([]GetActiveAssignmentsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveAssignmentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveAssignmentsByUserIDRow
	for rows.Next() {
		var i GetActiveAssignmentsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubTaskID,
			&i.AssignedAt,
			&i.UpdatedAt,
			&i.TypeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsBySubTaskID = `-- name: GetAssignmentsBySubTaskID :many
SELECT id, user_id, sub_task_id, assigned_at, updated_at FROM user_to_sub_task
WHERE sub_task_id = $1
ORDER BY assigned_at ASC
`

func (q *Queries) GetAssignmentsBySubTaskID(ctx context.Context, subTaskID int32) ([]UserToSubTask, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsBySubTaskID, subTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserToSubTask
	for rows.Next() {
		var i UserToSubTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubTaskID,
			&i.AssignedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsByTaskID = `-- name: GetAssignmentsByTaskID :many
SELECT uts.id, uts.user_id, uts.sub_task_id, uts.assigned_at, uts.updated_at FROM user_to_sub_task uts
JOIN sub_tasks st ON uts.sub_task_id = st.id
WHERE st.task_id = $1
ORDER BY uts.assigned_at ASC
`

func (q *Queries) GetAssignmentsByTaskID(ctx context.Context, taskID int32) ([]UserToSubTask, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserToSubTask
	for rows.Next() {
		var i UserToSubTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubTaskID,
			&i.AssignedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsByUserID = `-- name: GetAssignmentsByUserID :many
SELECT id, user_id, sub_task_id, assigned_at, updated_at FROM user_to_sub_task
WHERE user_id = $1
ORDER BY assigned_at DESC
`

func (q *Queries) GetAssignmentsByUserID(ctx context.Context, userID int32) ([]UserToSubTask, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserToSubTask
	for rows.Next() {
		var i UserToSubTask
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SubTaskID,
			&i.AssignedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSubTaskAssignment = `-- name: GetUserSubTaskAssignment :one
SELECT id, user_id, sub_task_id, assigned_at, updated_at FROM user_to_sub_task
WHERE id = $1
`

func (q *Queries) GetUserSubTaskAssignment(ctx context.Context, id int32) (UserToSubTask, error) {
	row := q.db.QueryRowContext(ctx, getUserSubTaskAssignment, id)
	var i UserToSubTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubTaskID,
		&i.AssignedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSubTaskAssignment = `-- name: UpdateUserSubTaskAssignment :one
UPDATE user_to_sub_task
SET updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, user_id, sub_task_id, assigned_at, updated_at
`

func (q *Queries) UpdateUserSubTaskAssignment(ctx context.Context, id int32) (UserToSubTask, error) {
	row := q.db.QueryRowContext(ctx, updateUserSubTaskAssignment, id)
	var i UserToSubTask
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SubTaskID,
		&i.AssignedAt,
		&i.UpdatedAt,
	)
	return i, err
}
