// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_to_type.sql

package db

import (
	"context"
	"database/sql"
)

const addUserTaskType = `-- name: AddUserTaskType :exec
INSERT INTO user_to_type (user_id, type_id)
VALUES ($1, $2)
ON CONFLICT (user_id, type_id) DO NOTHING
`

type AddUserTaskTypeParams struct {
	UserID int32
	TypeID int32
}

func (q *Queries) AddUserTaskType(ctx context.Context, arg AddUserTaskTypeParams) error {
	_, err := q.db.ExecContext(ctx, addUserTaskType, arg.UserID, arg.TypeID)
	return err
}

const countTaskTypeUsers = `-- name: CountTaskTypeUsers :one
SELECT COUNT(*) as user_count
FROM user_to_type
WHERE type_id = $1
`

func (q *Queries) CountTaskTypeUsers(ctx context.Context, typeID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTaskTypeUsers, typeID)
	var user_count int64
	err := row.Scan(&user_count)
	return user_count, err
}

const getTaskTypeUsers = `-- name: GetTaskTypeUsers :many
SELECT ut.user_id, ut.type_id, u.name, u.email, u.role_id, r.role_name, ut.created_at
FROM user_to_type ut
JOIN users u ON ut.user_id = u.id
JOIN roles r ON u.role_id = r.id
WHERE ut.type_id = $1
ORDER BY u.name
`

type GetTaskTypeUsersRow struct {
	UserID    int32
	TypeID    int32
	Name      string
	Email     string
	RoleID    int32
	RoleName  string
	CreatedAt sql.NullTime
}

func (q *Queries) GetTaskTypeUsers(ctx context.Context, typeID int32) ([]GetTaskTypeUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskTypeUsers, typeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskTypeUsersRow
	for rows.Next() {
		var i GetTaskTypeUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.TypeID,
			&i.Name,
			&i.Email,
			&i.RoleID,
			&i.RoleName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTaskTypes = `-- name: GetUserTaskTypes :many
SELECT ut.user_id, ut.type_id, t.type_name, t.description, t.created_at, t.updated_at, ut.created_at as assignment_created_at
FROM user_to_type ut
JOIN task_types t ON ut.type_id = t.id
WHERE ut.user_id = $1
ORDER BY t.type_name
`

type GetUserTaskTypesRow struct {
	UserID              int32
	TypeID              int32
	TypeName            string
	Description         sql.NullString
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	AssignmentCreatedAt sql.NullTime
}

func (q *Queries) GetUserTaskTypes(ctx context.Context, userID int32) ([]GetUserTaskTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTaskTypes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTaskTypesRow
	for rows.Next() {
		var i GetUserTaskTypesRow
		if err := rows.Scan(
			&i.UserID,
			&i.TypeID,
			&i.TypeName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllTaskTypeUsers = `-- name: RemoveAllTaskTypeUsers :exec
DELETE FROM user_to_type
WHERE type_id = $1
`

func (q *Queries) RemoveAllTaskTypeUsers(ctx context.Context, typeID int32) error {
	_, err := q.db.ExecContext(ctx, removeAllTaskTypeUsers, typeID)
	return err
}

const removeAllUserTaskTypes = `-- name: RemoveAllUserTaskTypes :exec
DELETE FROM user_to_type
WHERE user_id = $1
`

func (q *Queries) RemoveAllUserTaskTypes(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, removeAllUserTaskTypes, userID)
	return err
}

const removeUserTaskType = `-- name: RemoveUserTaskType :exec
DELETE FROM user_to_type
WHERE user_id = $1 AND type_id = $2
`

type RemoveUserTaskTypeParams struct {
	UserID int32
	TypeID int32
}

func (q *Queries) RemoveUserTaskType(ctx context.Context, arg RemoveUserTaskTypeParams) error {
	_, err := q.db.ExecContext(ctx, removeUserTaskType, arg.UserID, arg.TypeID)
	return err
}
